# -*- coding: utf-8 -*-
"""Simple App Dibimbing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DBeR_Z-4ueA7GCe27BofHRLIwUJzjZq7

# Task 1 & 2
"""

class Order:
  def __init__(self, order_id, customer_name, order_date, total_amount):
    self.order_id = order_id
    self.customer_name = customer_name
    self.order_date = order_date
    self.total_amount = total_amount

  def calculate_tax(self, tax_rate):
    return self.total_amount * tax_rate

  def display_order(self):
    print("Order ID:", self.order_id)
    print("Customer Name:", self.customer_name)
    print("Order Date:", self.order_date)
    print("Total Amount:", self.total_amount)

"""# Task 3"""

class OrderProcessor:
  def __init__(self):
    self.orders = []

  def add_order(self, order):
    self.orders.append(order)

  def calculate_total_revenue(self):
    total_revenue = sum(order.total_amount for order in self.orders)
    return total_revenue

  def calculate_total_tax(self, tax_rate):
    total_tax = sum(order.calculate_tax(tax_rate) for order in self.orders)
    return total_tax

  def display_orders(self):
    for order in self.orders:
      order.display_order()
      print()

"""# Task 4"""

if __name__ == "__main__":
  order1 = Order("100", "Muthia", "2024-03-14", 100.0)
  order2 = Order("101", "Aisyah", "2024-03-14", 15.0)
  order3 = Order("102", "Putri", "2024-03-15", 200.0)
  order4 = Order("103", "Ikhwanul", "2024-03-15", 50.0)
  order5 = Order("104", "Fahrudin", "2024-03-16", 30.0)
  order6 = Order("105", "Wanul", "2024-03-16", 90.0)

  order_processor = OrderProcessor()

  order_processor.add_order(order1)
  order_processor.add_order(order2)
  order_processor.add_order(order3)
  order_processor.add_order(order4)
  order_processor.add_order(order5)
  order_processor.add_order(order6)

  # Hitung total pendapatan dan total pajak
  tax_rate = 0.1  #pajak10%
  total_revenue = order_processor.calculate_total_revenue()
  total_tax = order_processor.calculate_total_tax(tax_rate)
  print("Total Revenue:", total_revenue)
  print("Total Tax:", total_tax)

  order_processor.display_orders()

